export const studentsData = {
  data: [
    {
      name: "John Doe",
      age: 20,
      gender: "Male",
      CGPA: 3.8,
      height: 180,
      weight: 75,
      activeInSports: true,
      distanceFromHomeToSchool: 5,
    },
    {
      name: "Jane Smith",
      age: 19,
      gender: "Female",
      CGPA: 3.9,
      height: 165,
      weight: 60,
      activeInSports: false,
      distanceFromHomeToSchool: 3,
    },
    {
      name: "Alice Johnson",
      age: 21,
      gender: "Female",
      CGPA: 3.7,
      height: 170,
      weight: 65,
      activeInSports: true,
      distanceFromHomeToSchool: 8,
    },
    {
      name: "Bob Brown",
      age: 22,
      gender: "Male",
      CGPA: 3.5,
      height: 175,
      weight: 80,
      activeInSports: true,
      distanceFromHomeToSchool: 10,
    },
    {
      name: "Charlie Davis",
      age: 20,
      gender: "Male",
      CGPA: 3.6,
      height: 178,
      weight: 72,
      activeInSports: false,
      distanceFromHomeToSchool: 7,
    },
    {
      name: "Diana Green",
      age: 18,
      gender: "Female",
      CGPA: 4.0,
      height: 160,
      weight: 55,
      activeInSports: true,
      distanceFromHomeToSchool: 6,
    },
    {
      name: "Ethan White",
      age: 19,
      gender: "Male",
      CGPA: 3.4,
      height: 185,
      weight: 85,
      activeInSports: false,
      distanceFromHomeToSchool: 4,
    },
    {
      name: "Fiona Black",
      age: 21,
      gender: "Female",
      CGPA: 3.8,
      height: 168,
      weight: 62,
      activeInSports: true,
      distanceFromHomeToSchool: 12,
    },
    {
      name: "George Wilson",
      age: 20,
      gender: "Male",
      CGPA: 3.2,
      height: 182,
      weight: 78,
      activeInSports: false,
      distanceFromHomeToSchool: 9,
    },
    {
      name: "Hannah King",
      age: 22,
      gender: "Female",
      CGPA: 3.9,
      height: 170,
      weight: 63,
      activeInSports: true,
      distanceFromHomeToSchool: 5,
    },
    {
      name: "Ian Lee",
      age: 18,
      gender: "Male",
      CGPA: 3.7,
      height: 175,
      weight: 70,
      activeInSports: true,
      distanceFromHomeToSchool: 8,
    },
    {
      name: "Jackie Martinez",
      age: 21,
      gender: "Female",
      CGPA: 3.5,
      height: 167,
      weight: 68,
      activeInSports: false,
      distanceFromHomeToSchool: 11,
    },
    {
      name: "Kevin Rodriguez",
      age: 19,
      gender: "Male",
      CGPA: 3.6,
      height: 180,
      weight: 76,
      activeInSports: true,
      distanceFromHomeToSchool: 6,
    },
    {
      name: "Laura Perez",
      age: 20,
      gender: "Female",
      CGPA: 3.8,
      height: 162,
      weight: 59,
      activeInSports: false,
      distanceFromHomeToSchool: 7,
    },
    {
      name: "Michael Thompson",
      age: 22,
      gender: "Male",
      CGPA: 3.9,
      height: 183,
      weight: 81,
      activeInSports: true,
      distanceFromHomeToSchool: 10,
    },
    {
      name: "Nina Sanchez",
      age: 21,
      gender: "Female",
      CGPA: 3.4,
      height: 169,
      weight: 64,
      activeInSports: true,
      distanceFromHomeToSchool: 4,
    },
    {
      name: "Oscar Scott",
      age: 19,
      gender: "Male",
      CGPA: 3.7,
      height: 177,
      weight: 73,
      activeInSports: false,
      distanceFromHomeToSchool: 9,
    },
    {
      name: "Paula Young",
      age: 18,
      gender: "Female",
      CGPA: 3.5,
      height: 165,
      weight: 58,
      activeInSports: true,
      distanceFromHomeToSchool: 3,
    },
    {
      name: "Quentin Allen",
      age: 20,
      gender: "Male",
      CGPA: 3.6,
      height: 181,
      weight: 79,
      activeInSports: false,
      distanceFromHomeToSchool: 7,
    },
    {
      name: "Rachel Harris",
      age: 21,
      gender: "Female",
      CGPA: 4.0,
      height: 172,
      weight: 60,
      activeInSports: true,
      distanceFromHomeToSchool: 2,
    },
  ],
};
